<?php
$url='C:\Users\管云凤\Desktop\聊天';
$content=file_get_contents($url);
$filename='tmp.jpg';
file_put_contents($filename,$content);
$url='C:\Users\管云凤\Desktop\头像';
file_put_contents('logo.png',file_get_contents($url));
//开始添加水印操作
$im=imagecreatetruecolor($filename);
$logo=imagecreatetruecolor('logo.png');
imagecopy($im,$logo,15,15,0,0,$size[0],$size[1]);
header("content-type:image/jpeg");
imagejpeg($im);
imagedestroy($im);